# Generated by Django 5.1 on 2025-04-14 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('sch_id', models.AutoField(primary_key=True, serialize=False)),
                ('sch_name', models.CharField(max_length=255)),
                ('sch_code_name', models.CharField(max_length=255)),
                ('adress', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('หญิง', 'หญิง'), ('ชาย', 'ชาย')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('หญิง', 'หญิง'), ('ชาย', 'ชาย')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('room', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.school')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClassroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.teacher')),
            ],
        ),
    ]
