# Generated by Django 5.0.4 on 2025-04-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_classroom_updated_on_school_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.classroom'),
            preserve_default=False,
        ),
    ]
